package fr.hugosimony.pokemontopaze.pokemon;

public enum CT {
	
	AIGUISAGE, DRACO_GRIFFE, CHOC_PSY, PLENITUDE, HURLEMENT, TOXIK,
	GRELE, GONFLETTE, CHOC_VENIN, PUIS_CACHEE, ZENITH,
	PROVOC, LASER_GLACE, BLIZZARD, ULTRALASER, MUR_LUMIERE,
	ABRI, DANSE_PLUIE, ATTERRISSAGE, RUNE_PROTECT, FRUSTRATION,
	LANCE_SOLEIL, ANTI_AIR, TONNERRE, FATAL_FOUDRE, SEISME,
	RETOUR, TUNNEL, PSYKO, BALL_OMBRE, CASSE_BRIQUE,
	REFLET, PROTECTION, CRADOVAGUE, LANCE_FLAMME, BOMBE_BEURK,
	TEMPETE_DE_SABLE, DEFLAGRATION, TOMBEROCHE, AEROPIQUE, TOURMENTE,
	FACADE, NITROCHARGE, REPOS, ATTRACTION, LARCIN,
	BALAYETTE, CHANT_CANON, ECHO, SURCHAUFFE, AILES_D_ACIER,
	EXPLOFORCE, ECO_SPHERE, FAUX_CHAGE, EBULLITION, DEGOMMAGE,
	RAYON_CHARGE, CHUTE_LIBRE, CALCINATION, A_LA_QUEUE, FEU_FOLLET,
	ACROBATIE, EMBARGO, EXPLOSION, GRIFFE_OMBRE, REPRESAILLES,
	VENGEANCE, GIGA_IMPACT, POLIROCHE, FLASH, LAME_DE_ROC,
	CHANGEECLAIR, CAGE_ECLAIR, GYROBALLE, DANSE_LAMES, SURVINSECTE,
	BOOST, PIETISOL, SOUFFLEGLACE, EBOULEMENT, PLAIE_CROIX,
	DRACO_QUEUE, HARCELEMENT, DIRECT_TOXIK, DEVOREVE, NOEUD_HERBE,
	VANTARDISE, BLABLA_DODO, DEMI_TOUR, CLONAGE, LUMINOCANON,
	DISTORSION, ECLAIR_FOU, MACHOUILLE, ABOIEMENT, FORCE_NATURE,
	VIBROBSCUR, POING_BOOST, ECLAT_MAGIQUE, CONFIDENCE,
	
	NULL;
	
	public static Moves getMove(CT ct) {
		
		switch(ct) {
		case AIGUISAGE:
			return Moves.AIGUISAGE;
		case DRACO_GRIFFE:
			return Moves.DRACO_GRIFFE;
		case CHOC_PSY:
			return Moves.CHOC_PSY;
		case PLENITUDE:
			return Moves.PLENITUDE;
		case HURLEMENT:
			return Moves.HURLEMENT;
		case TOXIK:
			return Moves.TOXIK;
		case GRELE:
			return Moves.GRELE;
		case GONFLETTE:
			return Moves.GONFLETTE;
		case CHOC_VENIN:
			return Moves.CHOC_VENIN;
		case PUIS_CACHEE:
			return Moves.PUIS_CACHEE;
		case ZENITH:
			return Moves.ZENITH;
		case PROVOC:
			return Moves.PROVOC;
		case LASER_GLACE:
			return Moves.LASER_GLACE;
		case BLIZZARD:
			return Moves.BLIZZARD;
		case ULTRALASER:
			return Moves.ULTRALASER;
		case MUR_LUMIERE:
			return Moves.MUR_LUMIERE;
		case ABRI:
			return Moves.ABRI;
		case DANSE_PLUIE:
			return Moves.DANSE_PLUIE;
		case ATTERRISSAGE:
			return Moves.ATTERRISSAGE;
		case RUNE_PROTECT:
			return Moves.RUNE_PROTECT;
		case FRUSTRATION:
			return Moves.FRUSTRATION;
		case LANCE_SOLEIL:
			return Moves.LANCE_SOLEIL;
		case ANTI_AIR:
			return Moves.ANTI_AIR;
		case TONNERRE:
			return Moves.TONNERRE;
		case FATAL_FOUDRE:
			return Moves.FATAL_FOUDRE;
		case SEISME:
			return Moves.SEISME;
		case RETOUR:
			return Moves.RETOUR;
		case TUNNEL:
			return Moves.TUNNEL;
		case PSYKO:
			return Moves.PSYKO;
		case BALL_OMBRE:
			return Moves.BALL_OMBRE;
		case CASSE_BRIQUE:
			return Moves.CASSE_BRIQUE;
		case REFLET:
			return Moves.REFLET;
		case PROTECTION:
			return Moves.PROTECTION;
		case CRADOVAGUE:
			return Moves.CRADOVAGUE;
		case LANCE_FLAMME:
			return Moves.LANCE_FLAMME;
		case BOMBE_BEURK:
			return Moves.BOMBE_BEURK;
		case TEMPETE_DE_SABLE:
			return Moves.TEMPETE_DE_SABLE;
		case DEFLAGRATION:
			return Moves.DEFLAGRATION;
		case TOMBEROCHE:
			return Moves.TOMBEROCHE;
		case AEROPIQUE:
			return Moves.AEROPIQUE;
		case TOURMENTE:
			return Moves.TOURMENTE;
		case FACADE:
			return Moves.FACADE;
		case NITROCHARGE:
			return Moves.NITROCHARGE;
		case REPOS:
			return Moves.REPOS;
		case ATTRACTION:
			return Moves.ATTRACTION;
		case LARCIN:
			return Moves.LARCIN;
		case BALAYETTE:
			return Moves.BALAYETTE;
		case CHANT_CANON:
			return Moves.CHANT_CANON;
		case ECHO:
			return Moves.ECHO;
		case SURCHAUFFE:
			return Moves.SURCHAUFFE;
		case AILES_D_ACIER:
			return Moves.AILES_D_ACIER;
		case EXPLOFORCE:
			return Moves.EXPLOFORCE;
		case ECO_SPHERE:
			return Moves.ECO_SPHERE;
		case FAUX_CHAGE:
			return Moves.FAUX_CHAGE;
		case EBULLITION:
			return Moves.EBULLITION;
		case DEGOMMAGE:
			return Moves.DEGOMMAGE;
		case RAYON_CHARGE:
			return Moves.RAYON_CHARGE;
		case CHUTE_LIBRE:
			return Moves.CHUTE_LIBRE;
		case CALCINATION:
			return Moves.CALCINATION;
		case A_LA_QUEUE:
			return Moves.A_LA_QUEUE;
		case FEU_FOLLET:
			return Moves.FEU_FOLLET;
		case ACROBATIE:
			return Moves.ACROBATIE;
		case EMBARGO:
			return Moves.EMBARGO;
		case EXPLOSION:
			return Moves.EXPLOSION;
		case GRIFFE_OMBRE:
			return Moves.GRIFFE_OMBRE;
		case REPRESAILLES:
			return Moves.REPRESAILLES;
		case VENGEANCE:
			return Moves.VENGEANCE;
		case GIGA_IMPACT:
			return Moves.GIGA_IMPACT;
		case POLIROCHE:
			return Moves.POLIROCHE;
		case FLASH:
			return Moves.FLASH;
		case LAME_DE_ROC:
			return Moves.LAME_DE_ROC;
		case CHANGEECLAIR:
			return Moves.CHANGEECLAIR;
		case CAGE_ECLAIR:
			return Moves.CAGE_ECLAIR;
		case GYROBALLE:
			return Moves.GYROBALLE;
		case DANSE_LAMES:
			return Moves.DANSE_LAMES;
		case SURVINSECTE:
			return Moves.SURVINSECTE;
		case BOOST:
			return Moves.BOOST;
		case PIETISOL:
			return Moves.PIETISOL;
		case SOUFFLEGLACE:
			return Moves.SOUFFLEGLACE;
		case EBOULEMENT:
			return Moves.EBOULEMENT;
		case PLAIE_CROIX:
			return Moves.PLAIE_CROIX;
		case DRACO_QUEUE:
			return Moves.DRACO_QUEUE;
		case HARCELEMENT:
			return Moves.HARCELEMENT;
		case DIRECT_TOXIK:
			return Moves.DIRECT_TOXIK;
		case DEVOREVE:
			return Moves.DEVOREVE;
		case NOEUD_HERBE:
			return Moves.NOEUD_HERBE;
		case VANTARDISE:
			return Moves.VANTARDISE;
		case BLABLA_DODO:
			return Moves.BLABLA_DODO;
		case DEMI_TOUR:
			return Moves.DEMI_TOUR;
		case CLONAGE:
			return Moves.CLONAGE;
		case LUMINOCANON:
			return Moves.LUMINOCANON;
		case DISTORSION:
			return Moves.DISTORSION;
		case ECLAIR_FOU:
			return Moves.ECLAIR_FOU;
		case MACHOUILLE:
			return Moves.MACHOUILLE;
		case ABOIEMENT:
			return Moves.ABOIEMENT;
		case FORCE_NATURE:
			return Moves.FORCE_NATURE;
		case VIBROBSCUR:
			return Moves.VIBROBSCUR;
		case POING_BOOST:
			return Moves.POING_BOOST;
		case ECLAT_MAGIQUE:
			return Moves.ECLAT_MAGIQUE;
		case CONFIDENCE:
			return Moves.CONFIDENCE;
		default:
			return Moves.NULL;
		}
	}

	public static CT getCT(int ctNumber) {
		
		switch(ctNumber) {
		case 1:
			return AIGUISAGE;
		case 2:
			return DRACO_GRIFFE;
		case 3:
			return CHOC_PSY;
		case 4:
			return PLENITUDE;
		case 5:
			return HURLEMENT;
		case 6:
			return TOXIK;
		case 7:
			return GRELE;
		case 8:
			return GONFLETTE;
		case 9:
			return CHOC_VENIN;
		case 10:
			return PUIS_CACHEE;
		case 11:
			return ZENITH;
		case 12:
			return PROVOC;
		case 13:
			return LASER_GLACE;
		case 14:
			return BLIZZARD;
		case 15:
			return ULTRALASER;
		case 16:
			return MUR_LUMIERE;
		case 17:
			return ABRI;
		case 18:
			return DANSE_PLUIE;
		case 19:
			return ATTERRISSAGE;
		case 20:
			return RUNE_PROTECT;
		case 21:
			return FRUSTRATION;
		case 22:
			return LANCE_SOLEIL;
		case 23:
			return ANTI_AIR;
		case 24:
			return TONNERRE;
		case 25:
			return FATAL_FOUDRE;
		case 26:
			return SEISME;
		case 27:
			return RETOUR;
		case 28:
			return TUNNEL;
		case 29:
			return PSYKO;
		case 30:
			return BALL_OMBRE;
		case 31:
			return CASSE_BRIQUE;
		case 32:
			return REFLET;
		case 33:
			return PROTECTION;
		case 34:
			return CRADOVAGUE;
		case 35:
			return LANCE_FLAMME;
		case 36:
			return BOMBE_BEURK;
		case 37:
			return TEMPETE_DE_SABLE;
		case 38:
			return DEFLAGRATION;
		case 39:
			return TOMBEROCHE;
		case 40:
			return AEROPIQUE;
		case 41:
			return TOURMENTE;
		case 42:
			return FACADE;
		case 43:
			return NITROCHARGE;
		case 44:
			return REPOS;
		case 45:
			return ATTRACTION;
		case 46:
			return LARCIN;
		case 47:
			return BALAYETTE;
		case 48:
			return CHANT_CANON;
		case 49:
			return ECHO;
		case 50:
			return SURCHAUFFE;
		case 51:
			return AILES_D_ACIER;
		case 52:
			return EXPLOFORCE;
		case 53:
			return ECO_SPHERE;
		case 54:
			return FAUX_CHAGE;
		case 55:
			return EBULLITION;
		case 56:
			return DEGOMMAGE;
		case 57:
			return RAYON_CHARGE;
		case 58:
			return CHUTE_LIBRE;
		case 59:
			return CALCINATION;
		case 60:
			return A_LA_QUEUE;
		case 61:
			return FEU_FOLLET;
		case 62:
			return ACROBATIE;
		case 63:
			return EMBARGO;
		case 64:
			return EXPLOSION;
		case 65:
			return GRIFFE_OMBRE;
		case 66:
			return REPRESAILLES;
		case 67:
			return VENGEANCE;
		case 68:
			return GIGA_IMPACT;
		case 69:
			return POLIROCHE;
		case 70:
			return FLASH;
		case 71:
			return LAME_DE_ROC;
		case 72:
			return CHANGEECLAIR;
		case 73:
			return CAGE_ECLAIR;
		case 74:
			return GYROBALLE;
		case 75:
			return DANSE_LAMES;
		case 76:
			return SURVINSECTE;
		case 77:
			return BOOST;
		case 78:
			return PIETISOL;
		case 79:
			return SOUFFLEGLACE;
		case 80:
			return EBOULEMENT;
		case 81:
			return PLAIE_CROIX;
		case 82:
			return DRACO_QUEUE;
		case 83:
			return HARCELEMENT;
		case 84:
			return DIRECT_TOXIK;
		case 85:
			return DEVOREVE;
		case 86:
			return NOEUD_HERBE;
		case 87:
			return VANTARDISE;
		case 88:
			return BLABLA_DODO;
		case 89:
			return DEMI_TOUR;
		case 90:
			return CLONAGE;
		case 91:
			return LUMINOCANON;
		case 92:
			return DISTORSION;
		case 93:
			return ECLAIR_FOU;
		case 94:
			return MACHOUILLE;
		case 95:
			return ABOIEMENT;
		case 96:
			return FORCE_NATURE;
		case 97:
			return VIBROBSCUR;
		case 98:
			return POING_BOOST;
		case 99:
			return ECLAT_MAGIQUE;
		case 100:
			return CONFIDENCE;
		default:
			return NULL;
		}
	}
	
	public static String getCTNumber(CT ct) {
		
		switch(ct) {
		case AIGUISAGE:
			return "01";
		case DRACO_GRIFFE:
			return "02";
		case CHOC_PSY:
			return "03";
		case PLENITUDE:
			return "04";
		case HURLEMENT:
			return "05";
		case TOXIK:
			return "06";
		case GRELE:
			return "07";
		case GONFLETTE:
			return "08";
		case CHOC_VENIN:
			return "09";
		case PUIS_CACHEE:
			return "10";
		case ZENITH:
			return "11";
		case PROVOC:
			return "12";
		case LASER_GLACE:
			return "13";
		case BLIZZARD:
			return "14";
		case ULTRALASER:
			return "15";
		case MUR_LUMIERE:
			return "16";
		case ABRI:
			return "17";
		case DANSE_PLUIE:
			return "18";
		case ATTERRISSAGE:
			return "19";
		case RUNE_PROTECT:
			return "20";
		case FRUSTRATION:
			return "21";
		case LANCE_SOLEIL:
			return "22";
		case ANTI_AIR:
			return "23";
		case TONNERRE:
			return "24";
		case FATAL_FOUDRE:
			return "25";
		case SEISME:
			return "26";
		case RETOUR:
			return "27";
		case TUNNEL:
			return "28";
		case PSYKO:
			return "29";
		case BALL_OMBRE:
			return "30";
		case CASSE_BRIQUE:
			return "31";
		case REFLET:
			return "32";
		case PROTECTION:
			return "33";
		case CRADOVAGUE:
			return "34";
		case LANCE_FLAMME:
			return "35";
		case BOMBE_BEURK:
			return "36";
		case TEMPETE_DE_SABLE:
			return "37";
		case DEFLAGRATION:
			return "38";
		case TOMBEROCHE:
			return "39";
		case AEROPIQUE:
			return "40";
		case TOURMENTE:
			return "41";
		case FACADE:
			return "42";
		case NITROCHARGE:
			return "43";
		case REPOS:
			return "44";
		case ATTRACTION:
			return "45";
		case LARCIN:
			return "46";
		case BALAYETTE:
			return "47";
		case CHANT_CANON:
			return "48";
		case ECHO:
			return "49";
		case SURCHAUFFE:
			return "50";
		case AILES_D_ACIER:
			return "51";
		case EXPLOFORCE:
			return "52";
		case ECO_SPHERE:
			return "53";
		case FAUX_CHAGE:
			return "54";
		case EBULLITION:
			return "55";
		case DEGOMMAGE:
			return "56";
		case RAYON_CHARGE:
			return "57";
		case CHUTE_LIBRE:
			return "58";
		case CALCINATION:
			return "59";
		case A_LA_QUEUE:
			return "60";
		case FEU_FOLLET:
			return "61";
		case ACROBATIE:
			return "62";
		case EMBARGO:
			return "63";
		case EXPLOSION:
			return "64";
		case GRIFFE_OMBRE:
			return "65";
		case REPRESAILLES:
			return "66";
		case VENGEANCE:
			return "67";
		case GIGA_IMPACT:
			return "68";
		case POLIROCHE:
			return "69";
		case FLASH:
			return "70";
		case LAME_DE_ROC:
			return "71";
		case CHANGEECLAIR:
			return "72";
		case CAGE_ECLAIR:
			return "73";
		case GYROBALLE:
			return "74";
		case DANSE_LAMES:
			return "75";
		case SURVINSECTE:
			return "76";
		case BOOST:
			return "77";
		case PIETISOL:
			return "78";
		case SOUFFLEGLACE:
			return "79";
		case EBOULEMENT:
			return "80";
		case PLAIE_CROIX:
			return "81";
		case DRACO_QUEUE:
			return "82";
		case HARCELEMENT:
			return "83";
		case DIRECT_TOXIK:
			return "84";
		case DEVOREVE:
			return "85";
		case NOEUD_HERBE:
			return "86";
		case VANTARDISE:
			return "87";
		case BLABLA_DODO:
			return "88";
		case DEMI_TOUR:
			return "89";
		case CLONAGE:
			return "90";
		case LUMINOCANON:
			return "91";
		case DISTORSION:
			return "92";
		case ECLAIR_FOU:
			return "93";
		case MACHOUILLE:
			return "94";
		case ABOIEMENT:
			return "95";
		case FORCE_NATURE:
			return "96";
		case VIBROBSCUR:
			return "97";
		case POING_BOOST:
			return "98";
		case ECLAT_MAGIQUE:
			return "99";
		case CONFIDENCE:
			return "100";
		default:
			return "0";
		}
	}
	
}
